version: '3.7'

services:
  API:
    container_name: APIMain
    image: apimain  # Utilise l'image 'apimain' (vous devez avoir cette image définie ou remplacer par une image disponible)
    environment:
      DB_host: mypostgres  # Hostname du service de base de données PostgreSQL
      DB_port: 5432  # Port utilisé par PostgreSQL (par défaut)
      DB_name: db  # Nom de la base de données
      DB_user: DB_user  # Utilisateur de la base de données
      DB_mdp: pwd  # Mot de passe de la base de données
    networks:
      - app-network  # Attache le service API au réseau 'app-network'
    depends_on:
      - database  # Dépend du service 'database' pour s'assurer que la base de données est démarrée correctement

  database:
    container_name: mypostgres
    image: mon-postgres:14.1  # Utilise l'image PostgreSQL version 14.1 (vous devez avoir cette image définie ou remplacer par une image disponible)
    environment:
      POSTGRES_DB: db  # Nom de la base de données PostgreSQL à créer
      POSTGRES_USER: DB_user  # Utilisateur PostgreSQL à créer
      POSTGRES_PASSWORD: pwd  # Mot de passe de l'utilisateur PostgreSQL
    networks:
      - app-network  # Attache le service de base de données au réseau 'app-network'
    volumes:
      - ./data:/var/lib/postgresql/data  # Montage d'un volume pour persister les données de PostgreSQL

  server:
    container_name: HTTP
    image: http  # Utilise l'image 'http' (vous devez avoir cette image définie ou remplacer par une image disponible)
    environment:
      BACKEND_hosts: API  # Configure l'adresse du backend pour le serveur HTTP
    ports:
      - "80:80"  # Mappe le port 80 du conteneur HTTP au port 80 de l'hôte
    networks:
      - app-network  # Attache le service serveur HTTP au réseau 'app-network'
    depends_on:
      - API  # Dépend du service 'API' pour s'assurer que l'API est démarrée correctement

networks:
  app-network:  # Définition du réseau personnalisé 'app-network'

volumes:
  data:  # Définition du volume nommé 'data' (cela semble être redondant et peut être supprimé)
