all:
  vars:
    ansible_user: centos  # Utilisateur Ansible
    ansible_ssh_private_key_file: ~/.ssh/id_rsa  # Clé privée SSH
  children:
    prod:
      hosts:
        paul.fourdrinoy.takima.cloud  # Hôte de production
