name: CI devops 2024

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test-backend:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'  # specify the distribution here

      - name: Build and test with Maven
        run:
          mvn clean verify --file simple-api-student-main/simple-api-student-main/pom.xml

      - name: Build image and push backend
        uses: docker/build-push-action@v3
        with:
          # relative path to the place where source code with Dockerfile is located
          context: simple-api-student-main/simple-api-student-main
          # Note: tags has to be all lower-case
          tags:  ${{secrets.DOCKERHUB_USERNAME}}/tp-devops-simple-api:latest

      - name: Build image and push database
        uses: docker/build-push-action@v3
        with:
          # relative path to the place where source code with Dockerfile is located
          context: Bdd
          # Note: tags has to be all lower-case
          tags:  ${{secrets.DOCKERHUB_USERNAME}}/tp-devops-simple-db:latest

      - name: Build image and push httpd
        uses: docker/build-push-action@v3
        with:
          # relative path to the place where source code with Dockerfile is located
          context: http
          # Note: tags has to be all lower-case
          tags:  ${{secrets.DOCKERHUB_USERNAME}}/tp-devops-simple-api:latest

      # - name: Login to Docker Hub
      #   run: echo "${{ secrets.TOKEN_DOCKERHUB}}" | docker login --username pfourdrinoy --password-stdin

      # - name: Build and push Docker image DB
      #   run: docker build -t pfourdrinoy/mydatabase:1.0 . | docker push pfourdrinoy/mydatabase:1.0

      # - name: Build and push Docker image API
      #   run: docker build -t pfourdrinoy/myapi:1.0 . | docker push pfourdrinoy/myapi:1.0

          
